package org.appinventor;
import com.google.appinventor.components.runtime.HandlesEventDispatching;
import com.google.appinventor.components.runtime.EventDispatcher;
import com.google.appinventor.components.runtime.Form;
import com.google.appinventor.components.runtime.Component;
import com.google.appinventor.components.runtime.HorizontalArrangement;
import com.google.appinventor.components.runtime.ListPicker;
import com.google.appinventor.components.runtime.Button;
import com.google.appinventor.components.runtime.WebViewer;
import com.google.appinventor.components.runtime.TextBox;
import com.google.appinventor.components.runtime.Clock;
import com.google.appinventor.components.runtime.BluetoothClient;
class Screen1 extends Form implements HandlesEventDispatching {
  private HorizontalArrangement 수평배치1;
  private ListPicker 목록_블루투스_연결하기;
  private Button 버튼_블루투스_연결끊기;
  private WebViewer 웹뷰어1;
  private HorizontalArrangement 수평배치2;
  private Button 레이저온;
  private Button 전진;
  private Button 레이저오프;
  private HorizontalArrangement 수평배치3;
  private Button 좌회전;
  private Button 정지;
  private Button 우회전;
  private HorizontalArrangement 수평배치4;
  private Button 스트리밍연결;
  private Button 후진;
  private Button 버튼7;
  private TextBox 스트리밍주소;
  private Clock 시계1;
  private BluetoothClient 블루투스클라이언트1;
  protected void $define() {
    this.AboutScreen("rccontrol");
    this.AlignHorizontal(3);
    this.AlignVertical(2);
    this.AppName("rccontrol");
    this.Scrollable(true);
    수평배치1 = new HorizontalArrangement(this);
    수평배치1.BackgroundColor(0x00FFFFFF);
    수평배치1.Height(-1010);
    수평배치1.Width(LENGTH_FILL_PARENT);
    목록_블루투스_연결하기 = new ListPicker(수평배치1);
    목록_블루투스_연결하기.BackgroundColor(0xFF97D8FF);
    목록_블루투스_연결하기.FontSize(10);
    목록_블루투스_연결하기.Height(LENGTH_FILL_PARENT);
    목록_블루투스_연결하기.Width(LENGTH_FILL_PARENT);
    목록_블루투스_연결하기.ItemBackgroundColor(0xFF0000FF);
    목록_블루투스_연결하기.Shape(1);
    목록_블루투스_연결하기.Text("블루투스 연결하기");
    목록_블루투스_연결하기.TextColor(0xFF000000);
    버튼_블루투스_연결끊기 = new Button(수평배치1);
    버튼_블루투스_연결끊기.BackgroundColor(0xFF97D8FF);
    버튼_블루투스_연결끊기.Enabled(false);
    버튼_블루투스_연결끊기.FontSize(10);
    버튼_블루투스_연결끊기.Height(LENGTH_FILL_PARENT);
    버튼_블루투스_연결끊기.Width(LENGTH_FILL_PARENT);
    버튼_블루투스_연결끊기.Shape(1);
    버튼_블루투스_연결끊기.Text("블루투스 연결끊기");
    웹뷰어1 = new WebViewer(this);
    웹뷰어1.Height(-1050);
    웹뷰어1.Width(LENGTH_FILL_PARENT);
    수평배치2 = new HorizontalArrangement(this);
    수평배치2.Height(-1010);
    수평배치2.Width(LENGTH_FILL_PARENT);
    레이저온 = new Button(수평배치2);
    레이저온.BackgroundColor(0xFFFF4C4C);
    레이저온.Height(LENGTH_FILL_PARENT);
    레이저온.Width(LENGTH_FILL_PARENT);
    레이저온.Shape(1);
    레이저온.Text("레이저ON");
    전진 = new Button(수평배치2);
    전진.BackgroundColor(0xFFFFC800);
    전진.Height(LENGTH_FILL_PARENT);
    전진.Width(LENGTH_FILL_PARENT);
    전진.Shape(1);
    전진.Text("전진");
    레이저오프 = new Button(수평배치2);
    레이저오프.BackgroundColor(0xFFFF4C4C);
    레이저오프.Height(LENGTH_FILL_PARENT);
    레이저오프.Width(LENGTH_FILL_PARENT);
    레이저오프.Shape(1);
    레이저오프.Text("레이저OFF");
    수평배치3 = new HorizontalArrangement(this);
    수평배치3.Height(-1010);
    수평배치3.Width(LENGTH_FILL_PARENT);
    좌회전 = new Button(수평배치3);
    좌회전.BackgroundColor(0xFFFFC800);
    좌회전.Height(LENGTH_FILL_PARENT);
    좌회전.Width(LENGTH_FILL_PARENT);
    좌회전.Shape(1);
    좌회전.Text("좌회전");
    정지 = new Button(수평배치3);
    정지.BackgroundColor(0xFFFFC800);
    정지.FontTypeface(3);
    정지.Height(LENGTH_FILL_PARENT);
    정지.Width(LENGTH_FILL_PARENT);
    정지.Shape(1);
    정지.Text("정지");
    우회전 = new Button(수평배치3);
    우회전.BackgroundColor(0xFFFFC800);
    우회전.Height(LENGTH_FILL_PARENT);
    우회전.Width(LENGTH_FILL_PARENT);
    우회전.Shape(1);
    우회전.Text("우회전");
    수평배치4 = new HorizontalArrangement(this);
    수평배치4.Height(-1010);
    수평배치4.Width(LENGTH_FILL_PARENT);
    스트리밍연결 = new Button(수평배치4);
    스트리밍연결.BackgroundColor(0xFFC6FFB4);
    스트리밍연결.Height(LENGTH_FILL_PARENT);
    스트리밍연결.Width(LENGTH_FILL_PARENT);
    스트리밍연결.Shape(1);
    스트리밍연결.Text("스트리밍연결");
    후진 = new Button(수평배치4);
    후진.BackgroundColor(0xFFFFC800);
    후진.Height(LENGTH_FILL_PARENT);
    후진.Width(LENGTH_FILL_PARENT);
    후진.Shape(1);
    후진.Text("후진");
    버튼7 = new Button(수평배치4);
    버튼7.BackgroundColor(0xFFC6FFB4);
    버튼7.Height(LENGTH_FILL_PARENT);
    버튼7.Width(LENGTH_FILL_PARENT);
    버튼7.Shape(1);
    스트리밍주소 = new TextBox(this);
    스트리밍주소.BackgroundColor(0xFFC8C6C6);
    스트리밍주소.Height(-1010);
    스트리밍주소.Width(LENGTH_FILL_PARENT);
    스트리밍주소.Hint("텍스트박스1 의 힌트");
    스트리밍주소.Text("192.168.0.11");
    시계1 = new Clock(this);
    블루투스클라이언트1 = new BluetoothClient(this);
  }
  public boolean dispatchEvent(Component component, String componentName, String eventName, Object[] params){
    return false;
  }
}